package com.czertainly.api.model.connector.signatures.formatter;

import com.czertainly.api.model.client.signing.profile.workflow.SigningWorkflowType;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.math.BigInteger;
import java.time.Instant;

/**
 * DTBS formatting request for the Timestamping workflow.
 *
 * <p>Carries Core-generated fields required for TSTInfo construction:
 * {@code serialNumber} (recorded in the Signature inventory) and
 * {@code signingTime} (captured from the time quality system).</p>
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@Schema(title = "TimestampingFormatDtbsRequestDto", description = "DTBS formatting request for Timestamping")
public class TimestampingFormatDtbsRequestDto extends FormatDtbsRequestDto {

    @Schema(
            description = "Serial number generated by Core, recorded in the Signature inventory",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private BigInteger serialNumber;

    @Schema(
            description = "Signing time captured by Core from the time quality system",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private Instant signingTime;

    public TimestampingFormatDtbsRequestDto() {
        super(SigningWorkflowType.TIMESTAMPING);
    }
}
